### ISSUE TITLE
Confusing navigation buttons in content.html and editContent.html

### ISSUE THREAD

**Issue by kaifanzhu** [uoForms/CCM#1]
Cannot apply css style to the navigation buttons on the bottom of the content.html page.
![image](https://cloud.githubusercontent.com/assets/12395587/11461238/3851aa08-96cd-11e5-8004-a6b55dad43d0.png)

The code that creates these buttons is in "quickforms" app "form.js" file, about line 200.
Under the comment " //get the last and next content and create navigation buttons."
![image](https://cloud.githubusercontent.com/assets/12395587/11461375/0220365e-96d0-11e5-9cce-bde2425beff9.png)

**Comment by aasam028** [comment]
We found out that buttons were used for  Francine CCM Navigation as it was used for the Old Francine.
Meaning the issue is coming from the CSS style and not the HTML.

**Comment by hannhow** [comment]
Changes made and published to Demo server. Pending retest.

**Comment by aasam028** [comment]
Tested
