### ISSUE TITLE
CSS Style - Scrambled Text at Tips Tab (Not showing in bullet points)

### ISSUE THREAD

**Issue by Sunerbones** [uoForms/CCM#11]
This problem occurs when the text needs to be displayed in bullet-point format even though it was edited in bullet points through the admin edit mode. Problems found in Week 1,3,5,6,8,9,10,11,14,17,18,20,23,24,27,28,29,32,33,34,37,38,39; New Born Week 1,2,4; Advantage of breast feeding; Signs of Labor; Warning signs in second trimester.
CSS style was blocked according to the HTML code.
<img width="1278" alt="screen shot 2016-01-22 at 11 23 24 am" src="https://cloud.githubusercontent.com/assets/11786914/12516359/110dfc14-c0fb-11e5-88df-b54737c26936.png">

**Comment by aasam028** [comment]
The Admin has the Bullet point in place but when it is viewed at the user's end it has a different look.

**Comment by Sunerbones** [comment]
What is the progress of this issue right now?

**Comment by hannhow** [comment]
No progress from my side.

**Comment by Sunerbones** [comment]
Please execute the following suggested way of fixing both CSS issues. (Images being cropped & Scrambled Text):
1. In content.html, add 2 more classes in the control part.
![image](https://cloud.githubusercontent.com/assets/11786914/12830707/ac08a9d6-cb5e-11e5-911c-df8122cd8860.png)
2. In custom.css, add ".classname" in the control part.
![image](https://cloud.githubusercontent.com/assets/11786914/12830765/fac289e8-cb5e-11e5-85b6-b2c7db02d515.png)

Then the problem should be fixed as follows:
![image](https://cloud.githubusercontent.com/assets/11786914/12830788/149da370-cb5f-11e5-96f0-32b59d45a211.png)

**Comment by hannhow** [comment]
Changes made. Please have it retested.
