### ISSUE TITLE
Images being Cropped

### ISSUE THREAD

**Issue by aasam028** [uoForms/CCM#14]
When the app is viewed on the phone, it is noticed that images are being cropped.
This needs to be resized and not cropped.

**Comment by Sunerbones** [comment]
What is the progress of this issue right now?

**Comment by hannhow** [comment]
No progress from my side.

**Comment by hannhow** [comment]
Guys, please let me know when you figure out how to use CSS to address this issue. @Sunerbones @aasam028 @hespee

**Comment by Sunerbones** [comment]
Please execute the following suggested way of fixing both CSS issues. (Images being cropped & Scrambled Text):
1. In content.html, add 2 more classes in the control part.
![image](https://cloud.githubusercontent.com/assets/11786914/12830707/ac08a9d6-cb5e-11e5-911c-df8122cd8860.png)
2. In custom.css, add ".classname" in the control part.
![image](https://cloud.githubusercontent.com/assets/11786914/12830765/fac289e8-cb5e-11e5-85b6-b2c7db02d515.png)

Then the problem should be fixed as follows:
![image](https://cloud.githubusercontent.com/assets/11786914/12830788/149da370-cb5f-11e5-96f0-32b59d45a211.png)

**Comment by hannhow** [comment]
Changed all the CSS attributes of the content from the database. Pending retest. Will have to figure out a systematic approach to completely address this issue.
