### ISSUE TITLE
"Up" tab should become a "Week x" Label

### ISSUE THREAD

**Issue by Sunerbones** [uoForms/CCM#15]
Change the 2 tabs to be 1 label, marked as the corresponding week number of the content page. 
![image](https://cloud.githubusercontent.com/assets/11786914/12832858/c9d13dfa-cb6a-11e5-804b-c28b9376a472.png)

**Comment by aasam028** [comment]
Rather than going "Up", clicking on the tab should go back to the current Week content.

**Comment by Sunerbones** [comment]
What is the progress of this issue right now? @hannhow

**Comment by hannhow** [comment]
No progress yet.

**Comment by hannhow** [comment]
Changes made. Pending retest.

**Comment by Sunerbones** [comment]
There is a confusion of the label mark for the new-born weeks! Should add "New-born" before  Week 1 to avoid the confusing. 
![3](https://cloud.githubusercontent.com/assets/11786914/13240142/006cf8bc-d9ae-11e5-8d1b-7047d65c6d8b.jpg)

**Comment by hannhow** [comment]
Changes made. Please have it retested.

**Comment by Sunerbones** [comment]
After the changes, found "Newborn - Week 1" tab shows incorrectly at the home page. 
<img width="661" alt="screen shot 2016-02-23 at 11 34 08 pm" src="https://cloud.githubusercontent.com/assets/11786914/13275770/7a99b836-da86-11e5-8ca3-72283b4fe526.png">

**Comment by hannhow** [comment]
Changes made. Pending retest.
