### ISSUE TITLE
Change Home Tab Name 

### ISSUE THREAD

**Issue by Sunerbones** [uoForms/CCM#16]
As agreed on the meeting, the "Home" tab name should be displayed as "Main".

<img width="1266" alt="screen shot 2016-01-22 at 11 41 06 am" src="https://cloud.githubusercontent.com/assets/11786914/12516749/1aa0db32-c0fd-11e5-9863-46d98abe3483.png">

**Comment by hannhow** [comment]
Changes made. Pending retest.

**Comment by Sunerbones** [comment]
Tested and found the tab name under editing mode is not changed. See screenshots as follows:
<img width="1278" alt="screen shot 2016-01-23 at 1 57 30 pm" src="https://cloud.githubusercontent.com/assets/11786914/12532096/493ae9ce-c1d9-11e5-937f-dcde24947c76.png">

**Comment by hannhow** [comment]
Changes made. Pending retest.
