### ISSUE TITLE
New image is not showing in the centre in mobile devices

### ISSUE THREAD

**Issue by Sunerbones** [uoForms/CCM#18]
![thumb_img_4006_1024](https://cloud.githubusercontent.com/assets/11786914/12620709/599147d6-c4eb-11e5-878a-9f7b00d0c283.jpg)

**Comment by banimilhem** [comment]
Hello Hao,

I have attached you an image for my solution for that issue you assigned
me. Please see the attachment below, you can find that just i changed the
left property form 0 px into -30 px and it is justified now.

Hope this would be the right solution :) !!!

Thanks

On Sat, Feb 27, 2016 at 11:05 PM, Hao Han <notifications@github.com> wrote:

> Assigned #18 <https://github.com/uoForms/CCM/issues/18> to @banimilhem
> <https://github.com/banimilhem>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/uoForms/CCM/issues/18#event-569481454>.
>



-- 
Regards,
Hind

**Comment by Sunerbones** [comment]
Retested on the mobile device, problem remains unchanged. Please update the solution to the actual code.

**Comment by banimilhem** [comment]
Yes, I will but after i meet Hao Today.

Thanks.

On Mon, Feb 29, 2016 at 2:46 PM, Panhua Zhu <notifications@github.com>
wrote:

> Retested on the mobile device, problem remains unchanged. Please update
> the solution to the actual code.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/uoForms/CCM/issues/18#issuecomment-190352398>.
>



-- 
Regards,
Hind

**Comment by banimilhem** [comment]
Changes made. Retesting Pending..
