### ISSUE TITLE
index needs login issue

### ISSUE THREAD

**Issue by kaifanzhu** [uoForms/CCM#2]
If access the app without resource name like "http://quickforms3.eecs.uottawa.ca/francine_CCM/", the tomcat will lead to index.html. But before that the auth.js will intercept and redirect to Login.html.
But if directly access the index.html like "http://quickforms3.eecs.uottawa.ca/francine_CCM/index.html" won't.
The code that checks the path needs login or not is in the "js/auth.js" file.
![image](https://cloud.githubusercontent.com/assets/12395587/11461426/0d4ff2a2-96d1-11e5-9cd5-7c92e805cadf.png)

**Comment by hannhow** [comment]
Changes made. Pending retest.

**Comment by aasam028** [comment]
Tested. This has been fixed.
