### ISSUE TITLE
Failed to load page content

### ISSUE THREAD

**Issue by Sunerbones** [uoForms/CCM#21]
<img width="1276" alt="screen shot 2016-01-28 at 3 45 58 pm" src="https://cloud.githubusercontent.com/assets/11786914/12658321/5800c6da-c5d6-11e5-8816-2ba168de8d91.png">

**Comment by hannhow** [comment]
Any context of this issue?

**Comment by Sunerbones** [comment]
It happened to both Francine (Week 20) and me (Week 40) while we were trying to update the content. Akosua had this problem this morning as well but it's ok for her later...Francine and I still have this problem no matter what  browser we use.. (tried chrome, safari and firefox)

**Comment by hannhow** [comment]
This interruption was caused by the full backup operations on SITE servers which is executed every 6 months. Please have it retested after Monday (Feb. 1st)

**Comment by Sunerbones** [comment]
@hannhow  The problem is still there when I open the page for Week 20, Week 21 and Week 40.  The rest pages work well.

**Comment by hannhow** [comment]
Did anyone change the content for these weeks?

**Comment by Sunerbones** [comment]
@hannhow  No, we were all trying to update the content but these 3 pages cannot even be opened during the course.

**Comment by hannhow** [comment]
There might be some errors with previous html tags for those weeks. I have reset the content. Please add new one to it.
