### ISSUE TITLE
Home Page Layout Need Update

### ISSUE THREAD

**Issue by Sunerbones** [uoForms/CCM#24]
1. "About US" button to be moved from week content page to the home page.
2. Resize the buttons and make sure they are not covered when squeeze the window.
![image](https://cloud.githubusercontent.com/assets/11786914/12831448/51f62bd6-cb62-11e5-95e2-491967934a8b.png)

**Comment by hannhow** [comment]
Changes made. Pending retest.

**Comment by Sunerbones** [comment]
![img](https://cloud.githubusercontent.com/assets/11786914/12934229/0a5a6966-cf5b-11e5-8153-3018ae053eca.jpg)
Delete "about" button in the weekly content page.

**Comment by hannhow** [comment]
Done. Pending retest.
