### ISSUE TITLE
"AGE" to be Added to the Initial Subscription

### ISSUE THREAD

**Issue by aasam028** [uoForms/CCM#25]
There should be a drop down for users to select their age range

![age](https://cloud.githubusercontent.com/assets/15662347/12837453/f38bfb5a-cb90-11e5-9912-1a632e10a819.PNG)

**Comment by Sunerbones** [comment]
Need to inform Francine that she will have to develop a privacy policy in order to collect the age information.

**Comment by hannhow** [comment]
Pending retest.
