### ISSUE TITLE
Tab Name Update

### ISSUE THREAD

**Issue by Sunerbones** [uoForms/CCM#27]
Francine would like to upgrade the whole content of the app and all the tab names should be changed as follows:

1. Pregnancy
2. Movement
3. Nutrition
4. Wisdom
5. Decolonization

<img width="1271" alt="screen shot 2016-02-05 at 4 39 16 pm" src="https://cloud.githubusercontent.com/assets/11786914/12860307/ba893e82-cc29-11e5-9e02-1bcb95a7366b.png">

**Comment by hannhow** [comment]
Changes made. Pending checking in.

**Comment by hannhow** [comment]
Changes made. Pending retest.
