### ISSUE TITLE
Upload All New Pictures to the Server

### ISSUE THREAD

**Issue by Sunerbones** [uoForms/CCM#28]
As requested by Francine, new images should replace all current ones we have been using.

**Comment by hannhow** [comment]
Pictures uploaded. Please use this relative path "img/content/" + file name as the path for pictures (replace space with %20). For example, if you try to use "perfect family shot web.jpg", the full path would be "img/content/perfect%20family%20shot%20web.jpg". Original files are to be shared via Google Drive.

**Comment by hannhow** [comment]
Files shared.

**Comment by hannhow** [comment]
Please have it closed if there is no concern regarding uploading pictures to server.
