### ISSUE TITLE
Cannot Update Content Using "Edit" Function

### ISSUE THREAD

**Issue by Sunerbones** [uoForms/CCM#29]
I was trying to update the "Pregnancy" tab content under edit mode, however, I am not able to update it as once submitted, the current page becomes no longer accessible (as picture showed below). I have tried week 5 and week 6...
<img width="1197" alt="screen shot 2016-02-14 at 9 52 10 pm" src="https://cloud.githubusercontent.com/assets/11786914/13038770/3a71f78c-d365-11e5-9de4-08300886c9e8.png">

**Comment by hannhow** [comment]
It appears to have some HTML tag issues or JSON format issues. Reset the content will address this temporarily. Will have to dig into this.

**Comment by hannhow** [comment]
Please have it retested and closed if there is no issue editing or displaying the content.
