### ISSUE TITLE
CSS - Second&Third Level Bullet Points Display Problem

### ISSUE THREAD

**Issue by Sunerbones** [uoForms/CCM#30]
This problem occurs when there's a second or third level bullet points needed in the text. 
Problems found in Week 22.
Editing Interface:
<img width="1266" alt="screen shot 2016-02-22 at 7 39 48 pm" src="https://cloud.githubusercontent.com/assets/11786914/13237727/1acd6eb0-d99c-11e5-9ffb-710fffcf547b.png">

User Screen Display:
<img width="1272" alt="screen shot 2016-02-22 at 7 39 31 pm" src="https://cloud.githubusercontent.com/assets/11786914/13237735/2ca2adda-d99c-11e5-96b8-35393acb4c72.png">

**Comment by hannhow** [comment]
Please compare the difference of CSS between these two modes.

**Comment by Sunerbones** [comment]
Compared the code between 2 modes, findings as follows:
1. The actual content code is no difference between the 2 modes.
2. The second and third level tag doesn't apply to its actual content in the user mode. See screenshots below:
**Edit Mode:**
![image](https://cloud.githubusercontent.com/assets/11786914/13239781/e7b30030-d9aa-11e5-895c-b0fb58e3a8fd.png)
and its CSS source:
![image](https://cloud.githubusercontent.com/assets/11786914/13239802/1bcf0468-d9ab-11e5-99d4-295ec551b344.png)

**User Mode:
**![image](https://cloud.githubusercontent.com/assets/11786914/13239788/fb093f3c-d9aa-11e5-99e7-4aa7f6f39fd3.png)
and its CSS source:
![image](https://cloud.githubusercontent.com/assets/11786914/13239807/260c1132-d9ab-11e5-85d4-cf56b818b1c1.png)

**Comment by hannhow** [comment]
It is li's attributes that matters, not ul.

**Comment by hannhow** [comment]
Deleted attribute "float: left;" of element li. Should be displaying properly right now. Pending retest.
