### ISSUE TITLE
Add "Up" Button at the Top 

### ISSUE THREAD

**Issue by Sunerbones** [uoForms/CCM#31]
Add another "Up" Button at the top of the content pages. 
<img width="1275" alt="screen shot 2016-02-29 at 2 38 24 pm" src="https://cloud.githubusercontent.com/assets/11786914/13406593/63ffdefa-def2-11e5-8138-4eec395a5479.png">

**Comment by hannhow** [comment]
Did some investigation.

This function is implemented in quickforms\js\dom\form\form.js - parseCcmContent.

**Comment by hannhow** [comment]
Seems that it uses a callback function which is executed after the content is filled in.

**Comment by banimilhem** [comment]
Changes made. Pending retest
