### ISSUE TITLE
Cannot Access Week 26

### ISSUE THREAD

**Issue by Sunerbones** [uoForms/CCM#32]
Francine was trying to update some content by herself this morning but the week 26 becomes not accessible again. It happens at my side as well.

![image](https://cloud.githubusercontent.com/assets/11786914/13508517/49b0d896-e155-11e5-97e0-25e1d8b7ea74.png)

**Comment by hannhow** [comment]
Which tab did she change?

**Comment by Sunerbones** [comment]
Wisdom tab only.

**Comment by hannhow** [comment]
You may set the content of that tab to null and re-edit it.

**Comment by Sunerbones** [comment]
I will try and see if that works.
