### ISSUE TITLE
Add "Help" Button/Resource under Edit Mode

### ISSUE THREAD

**Issue by Sunerbones** [uoForms/CCM#35]
Add content update help instruction under the edit mode. Instruction files are to be shared through e-mail. @hannhow @banimilhem

**Comment by hannhow** [comment]
@Sunerbones  Please specify your requirements so that @banimilhem can understand what to do.

**Comment by Sunerbones** [comment]
Requirements and instructions were specified in the instruction files shared. We need a "Help" button that right locates next to "Report a Problem | Logout" button to enable "content update instructions" information showing at a new web page, which is only visible under the "Edit" admin mode.
<img width="1280" alt="screen shot 2016-03-25 at 1 40 45 pm" src="https://cloud.githubusercontent.com/assets/11786914/14050002/3734aada-f28f-11e5-9969-c4f514a79420.png">

**Comment by banimilhem** [comment]
Help Button is added. Retesting Pending.

**Comment by banimilhem** [comment]
helpInstructions web page is updated. Retesting Pending

**Comment by banimilhem** [comment]
Changes made. Retesting Pending.
