### ISSUE TITLE
E-mail Notification Message Need Modification

### ISSUE THREAD

**Issue by Sunerbones** [uoForms/CCM#36]
Further details will be posted later when Francine approves. This first comment is to record the issue for keeping tracks.

**Comment by Sunerbones** [comment]
E-mail message now is confirmed with Francine, please update with the following message template in the database.

“Dear Subscriber,
 
You are 22 weeks pregnant!

Please click on the link below to see your week 22 pregnancy update!

 http://quickforms3.eecs.uottawa.ca/pregapp/content.html?id=23 

 Celebrating Creation"

**Comment by hannhow** [comment]
@banimilhem Please stop working on this issue. I have fixed that.

**Comment by hannhow** [comment]
Pending retest.
