### ISSUE TITLE
Delete All New-born Weeks

### ISSUE THREAD

**Issue by Sunerbones** [uoForms/CCM#37]
Francine would like to delete all new-born weeks. In parallel, the e-mail notification scheme should be adjusted as well without sending emails after week 40.

**Comment by hannhow** [comment]
How about Signs of Labor and Advantages of Breast Feeding?

**Comment by Sunerbones** [comment]
Shouldn't be there as well. The plan was to just have support during pregnancy.

**Comment by hannhow** [comment]
Changes made. Pending retest.
