### ISSUE TITLE
Change Homepage Image

### ISSUE THREAD

**Issue by Sunerbones** [uoForms/CCM#41]
Francine would like to replace the current homepage image with the following one:

![quem-eight-sm_7722834410_o](https://cloud.githubusercontent.com/assets/11786914/14796896/b839aaaa-0afd-11e6-84c6-78a252a4b12d.jpg)

**Comment by banimilhem** [comment]
Changes Made. retest Pending.

**Comment by Sunerbones** [comment]
Francine still would like to change

**Comment by banimilhem** [comment]
Changes made. Retest Pending
