### ISSUE TITLE
Add Privacy Policy

### ISSUE THREAD

**Issue by Sunerbones** [uoForms/CCM#42]
Add "Privacy Policy" text and make it hyperlinked to the policy statement page upon click.

Put it underneath the copyright information.
<img width="258" alt="screen shot 2016-05-01 at 1 18 03 pm" src="https://cloud.githubusercontent.com/assets/11786914/14943137/3bec3976-0f9f-11e6-91d2-b2ad312fa335.png">

**Comment by Kawthar1** [comment]
Change made.Pending retest.

**Comment by aasam028** [comment]
Tested. 
<img width="1001" alt="privacy" src="https://cloud.githubusercontent.com/assets/15662347/15718569/0e828bc0-27fa-11e6-9783-901f0be7bc41.PNG">

**Comment by aasam028** [comment]
Below changes need to be done:

- The Pop up should be resized and the main application needs to show on the sides .(only Vertical Scroll)

- The font spacing needs to be edited

-  Content layout
