### ISSUE TITLE
Add Terms of Use

### ISSUE THREAD

**Issue by Sunerbones** [uoForms/CCM#43]
Add "Terms of Use" on the subscription dialog window and make it hyperlinked to the terms page. Apply a checkbox ahead of the statement where users must choose to agree in order to receive weekly notification service.

<img width="923" alt="screen shot 2016-05-01 at 1 22 14 pm" src="https://cloud.githubusercontent.com/assets/11786914/14943155/bf77b7b6-0f9f-11e6-8cc0-f7a5b1012aa0.png">

**Comment by aasam028** [comment]
This should work in the same way as Privacy Policy.

- The check box should be on the right side of the Terms of Use.
It can be in the form " I agree to the Terms of Use" + Check box

**Comment by chandank28** [comment]
changes has been done, waiting for retesting

**Comment by aasam028** [comment]
•The check box should be on the right side of the Terms of Use. It can be in the form " I agree to the Terms of Use" + Check box 

Also, the terms of use should be a  pop up message like the Privacy policy.

<img width="888" alt="subscribe" src="https://cloud.githubusercontent.com/assets/15662347/15937208/f1df5f00-2e3b-11e6-9b0c-dad8f16ae5dc.PNG">

**Comment by chandank28** [comment]
changes for email validation and due date is done.
about the age dropdown i confirm with hind and other team members the original code doesnt have the drop down age list.
provide me the age factor list so i can create dropdown.
i tired to make term of use into html link page its not working right now .
