### ISSUE TITLE
Home Page Design - The Bottom Copyright Banner

### ISSUE THREAD

**Issue by Sunerbones** [uoForms/CCM#9]
Copyright information text should be moved to the centre. 
<img width="1270" alt="a3a3c2d2-b978-11e5-9cb8-6c26068046cc" src="https://cloud.githubusercontent.com/assets/11786914/12285238/12a214e2-b986-11e5-93c1-2afa6d1800fb.png">

**Comment by hannhow** [comment]
Changes made. Pending retest.
